# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e2ffe53a2e50c04e75df366bc1f2bf631bcf0d3559f9fcd525cc175b23aac75823a78db776f9b104fd2ea7d95fd412d55fa8b33a79e75429db928fb7f962ae

test:
  secret_key_base: cb5ad3037bf93b8e20f949c6bce316978479ee52a0452d96e8a632027176b61e17b4c795e1604ce0e7a9f46a1f1d71add470630a24ab8f577789a2badf7cffef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
